config/routes.rb
Hackday::Application.routes.draw do
  resources :logs

  match 'login' => 'sessions#new'
  match 'logout' => 'sessions#destroy'
  match 'signup' => 'users#new'
  match 'home' => 'home#index'
  match 'ui' => 'home#ui'
  match 'welcome' => 'welcome#index'
  match 'chat' => 'chat#index'
  match 'pusher/auth' => 'pusher#auth'

  resources :users
  resource :sessions

  root :to => 'home#index'

end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :user
  attr_accessible :at, :body, :timestamp
  
  def uid
    user.uid
  end
  
  def name
    user.name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :name
  has_secure_password
  validates_presence_of :password, :on => :create
end

app/controllers/application_controller.rb
require 'net/http'

class ApplicationController < ActionController::Base
  # protect_from_forgery
  # force_ssl
  
  # after_filter :set_access_control_headers
  # def set_access_control_headers 
  #   headers['Access-Control-Allow-Origin'] = '*' 
  #   headers['Access-Control-Request-Method'] = '*' 
  # end
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user
  
  def logged_in?
    current_user.present? ? true : false
  end
  helper_method :logged_in?
  
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def index
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    schedule_now_and_next_url = "http://www.arte.tv/tvhack/tvguide/epg/live/D/L3/10.json"#?#{Time.now.to_i}"

    schedule_now_and_next = parse_json(schedule_now_and_next_url)
    @schedule_now = schedule_now_and_next["abstractBroadcastList"][0]
    @schedule_next = schedule_now_and_next["abstractBroadcastList"]

    date_today = Date.today.strftime("%Y-%m-%d")
    date_yesterday = Date.yesterday.strftime("%Y-%m-%d")
    schedule_url = "http://www.arte.tv/tvhack/tvguide/epg/schedule/D/L3/#{date_yesterday}/#{date_today}.json"#?#{Time.now.to_i}"

    schedule_day = parse_json(schedule_url)
    schedule_previous = []
    previous_found = false
    schedule_day["abstractBroadcastList"].each_with_index {|program, index|
      if program["BID"] == @schedule_now["BID"]
        previous_found = true
      end

      unless previous_found
        schedule_previous << schedule_day["abstractBroadcastList"][index]
      end
    }
    @schedule_previous = schedule_previous.reverse.take(9)
  end

  def parse_json(url)
    return JSON.parse(Net::HTTP.get_response(URI.parse(url)).body)
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def index
    @logs = Log.scoped.includes(:user)
    
    if params[:at_time]
      # Format: "2012-10-20-10-00"
      at = DateTime.strptime(params[:at],"%Y-%m-%d-%H-%M").to_time
      @logs = @logs.where("at >= ?", at).where("at <= ?", at + 1.minute)
    end
    
    if params[:from] && params[:to]
      # Format: 0-n
      # In Seconds
      # 1st minute == timestamp = 60
      @logs = @logs.where("timestamp >= ? AND timestamp <= ?", params[:from], params[:to])
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @logs.to_json(:methods => [:uid, :name]) }
    end
  end
  
  def new
    @log = Log.new
  end
  
  def create
    if logged_in?
      @log = Log.new(params[:log])
      @log.user_id = current_user.id
      if params[:time].present?
        @log.at = params[:time]
      else
        @log.at = Time.now
      end
      if @log.save
        logger.info "awesome, #{current_user.email} tagged a video at #{@log.at}"
        Pusher['comments'].trigger('comment', { :body => @log.body, :user_id => @log.user_id, :short_time => @log.at.strftime("%H:%M"), :name => @log.user.name, :uid => @log.user.uid, :id => @log.id, :timestamp => @log.timestamp })
      end
      render json: @log, status: :created, location: @log
    else
      flash[:notice] = 'not logged in!'
      logger.info "something went wrong :( #{current_user.to_json}"
      redirect_to new_log_path
    end
  end
end

app/controllers/pusher_controller.rb
class PusherController < ApplicationController
  protect_from_forgery :except => :auth

  def auth
    if current_user
      response = Pusher[params[:channel_name]].authenticate(params[:socket_id], {
        :user_id => current_user.id,
        :user_info => { # => optional - for example
          :name => current_user.name,
          :email => current_user.email,
          :uid => current_user.uid
        }
      })
      render :json => response
    else
      render :text => "Forbidden", :status => '403'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      logger.info "logged in!"
      redirect_to root_url
    else
      logger.info "invalid login!!!"
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

  def show
    render "new"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "you're in, awesome!"
    else
      render "new"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat/index.html.erb
<div style="background-color: white">
  <h2>Realtime debug:</h2>
  <div id="debug_window">
  </div>

  <%= form_for Log.new, :remote => true do |f| %>
    <p>
      <%= f.text_field :body, :autocomplete => "off" %>
      <%= f.text_field :timestamp, :autocomplete => "off", :style => "width: 30px" %>
      <%= f.submit "Send" %>
    </p>
  <% end %>

  <hr />

  <div id="count">Loading members count …</div>

  <ul id="members">
  </ul>
</div>

app/views/home/ui.html.erb
  <div id="container">
    <div id="prev" class="sidebar">
      <a href="#" class="sidebar-video">
        <div class="sidebar-title">Sendung verpasst?</div>
        <%= image_tag("ui/missed-video.jpg") %>
        <h3>Modelsuche in Sibirien</h3>
        19:15 - 20:15 Uhr
      </a>
    </div>

    <div id="current">
      <div id="video">
        <%= image_tag("ui/video.png") %>
        <a href="#" id="video-trigger" class="button">
          Video jetzt anschauen
        </a>
      </div>
      <div id="current-video">
        <div id="teaser-button">
          <%= image_tag("ui/teaser-video.jpg") %>
        </div>
        <div id="description">
          <div id="nowon">Jetzt läuft:</div>
          <h1>Das Coolness-Diktat</h1>
          <h2>
            20:15 - 22:15 Uhr
          </h2>
          <p>
            Die Produkte der Firma Apple, seien es Computer oder Telefone, vermitteln den Käufern beziehungsweise Nutzern eine bestimmte Lebensart und die Zugehörigkeit zu einer besonderen - oft auch als elitär bezeichneten - Gruppe der Gesellschaft, die äußerst anziehend wirkt.
          </p>
        </div>
      </div>
    </div>
    
    <div id="next" class="sidebar">
      <a href="#" class="sidebar-video">
        <div class="sidebar-title">Nächste Sendung:</div>
        <%= image_tag("ui/preview-video.jpg") %>
        <h3>Die Arte Reportage</h3>
        22:15 - 22:35 Uhr
      </a>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackday</title>
  <%= csrf_meta_tags %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
  <script src="http://js.pusher.com/1.12/pusher.min.js" type="text/javascript"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, target-densitydpi=device-dpi, user-scalable=no" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ui/apple-touch-icon-72x72.png" />
  
  <meta property="og:title" content="TV Hackday 2012" />
  <meta property="og:description" content="ROFL! Die Hasen-Stelle ist …" />
  <meta property="og:image" content="https://tivipeek.blob.core.windows.net/public/share_preview.png" />
  <meta property="og:url" content="http://www.tivipeek.com/hackday2012/" />
  <link rel="image_src" type="image/png" href="https://tivipeek.blob.core.windows.net/public/share_preview.png" />
  
  <%= yield(:head) %>
</head>
<%
if logged_in?
  user_id = current_user.id
else
  user_id = 0
end
%>
<body class="ui" data-current-id="<%= user_id %>">
  
  <% flash.each do |name, message| %>
    <% message_type = (name == :notice ? "success" : name) %>
    <div id="flash_message">
      <%= message.html_safe %>
    </div>
  <% end %>
  
  <%= yield %>
  
</body>
</html>

app/views/layouts/ui.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackday</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, target-densitydpi=device-dpi, user-scalable=no" />
  <meta name="apple-mobile-web-app-capable" content="yes">
</head>
<body class="ui">

  <%= yield %>

</body>
</html>

app/views/logs/index.html.erb
<h1>All logs</h1>

<dl>
  <% @logs.each do |log| %>
    <dt>
      <%= log.user.email %> wrote at <%= log.at %>
    </dt>
    <dd>
      <%= log.body %>
    </dd>
  <% end %>
</dl>

<% if logged_in? %>
  <p>
    <%= link_to 'new log (form)', new_log_path %>
  </p>
<% end %>

app/views/logs/new.html.erb
<%= form_for @log do |f| %>
  <p>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </p>
  <p>
    <%= f.label :timestamp %>
    <%= f.text_field :timestamp %>
  </p>
  <p>
    <%= f.label :at %>
    <%= f.datetime_select :at %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>something went wrong :|</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/welcome/_index.html.erb
<h1>hackday fake-wiki</h1>
<h2>written in germish language</h2>

<h3>javascript files</h3>
<p>
  javascript files path:<br />
  - hackday/app/assets/javascripts<br />
  werden automatisch geladen - ansonsten app/assets/javascripts/application.js editieren
</p>

<h3>images</h3>
<p>
  images path<br />
  - hackday/app/assets/images/
</p>

<hr />

<h3>filesharing</h3>
<p>
  /share
</p>

<hr />

<h3>view all <%= link_to "logs", logs_path %></h3>

<hr />

<ul>
  <li>
    <%= link_to "root", root_path %>
  </li>
  <li>
    <%= link_to "home", home_path %>
  </li>
  <li>
    <%= link_to "view all logs", logs_path %>
  </li>
</ul>


<p>
  have fun.
</p>

app/views/welcome/index.html.erb
<% content_for :head do %>
  <script type="text/javascript" >
  var currentBrdcst = {};
  var arteCTX = new ArteContext();
  jQuery(function($) {
      $.extend({
          serializeJSON: function(obj) {
              var t = typeof(obj);
              if(t != "object" || obj === null) {
                  // simple data type
                  if(t == "string") obj = '"' + obj + '"';
                  return String(obj);
              } else {
                  // array or object
                  var json = [], arr = (obj && obj.constructor == Array);

                  $.each(obj, function(k, v) {
                      t = typeof(v);
                      if(t == "string") v = '"' + v + '"';
                      else if (t == "object" & v !== null) v = $.serializeJSON(v)
                      json.push((arr ? "" : '"' + k + '":') + String(v));
                  });

                  return (arr ? "[" : "{") + String(json) + (arr ? "]" : "}");
              }
          }
      });
  });
  $(document).ready( function() {
  	$("#test").bind("click", function() {
  		arteCTX.load(function(prev,current,next) {			
  			$('#tarea').text("===prev:" + $.serializeJSON(prev) + 
  							 "\\n\n\n===current:" + $.serializeJSON(current) +
  							 "\n\n\n===next:" + $.serializeJSON(next));
  		});
  	});
  });
  </script>
<% end %>
<button id="test" >test</button>
<textarea id="tarea" rows="20" cols="150"></textarea>